### ISSUE TITLE
8.01 updates needed

### ISSUE THREAD

**Issue by disc0infern0** [Lumiahna/RaidBuffStatus_Continued#3]
Slight edits needed to make this compatible with the pre-patch:
Edit calls to UnitBuff to account for removal of the rank - moving most variables one to the left.
Edit calls to the chat-addon calls (registeraddonprefix etc) and prefix them with C_CHAT_INFO.

it then works!

**Comment by disc0infern0** [comment]
[LibGroupInSpecT-1.1 txt](https://github.com/Lumiahna/RaidBuffStatus_Continued/files/2220059/LibGroupInSpecT-1.1.txt)
[Core.lua.txt](https://github.com/Lumiahna/RaidBuffStatus_Continued/files/2220061/Core.lua.txt)

**Comment by Lumiahna** [comment]
Hello @disc0infern0 ,
I applied your fix, it seems to work.
I'll update asap the addons with BFA's changes.
Cheers

**Comment by disc0infern0** [comment]
Hey, thanks :)   I did find however a couple of further bugs/
1) the UnitPower call needed to be used instead of UnitMana
2) the combat log wasn't being parsed correctly - the new 8.0 call doesn't pass back event as the first parameter, and so taunt warnings were not working. Fix attached.

[Core.lua.txt](https://github.com/Lumiahna/RaidBuffStatus_Continued/files/2226462/Core.lua.txt)
